name: Archive

on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  contents:
    name: Archive contents (${{ matrix.sitemaps }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sitemaps:
        #fandom automaticaly generates a sitemap of 3 sitemaps, but since the english one is too big and makes the workflow to timeout, the single ones are written separately to spin up different workflows
          - https://winx.fandom.com/sitemap-newsitemapxml-NS_0-id-1870-111148.xml
          - https://winx.fandom.com/sitemap-newsitemapxml-NS_14-id-1851-111149.xml
          - https://services.fandom.com/discussions-sitemap/sitemap/6708
          #end english
          - https://winx.fandom.com/bg/sitemap-newsitemapxml-index.xml
          - https://winx.fandom.com/ca/sitemap-newsitemapxml-index.xml
          - https://winx.fandom.com/cs/sitemap-newsitemapxml-index.xml
          - https://winx.fandom.com/es/sitemap-newsitemapxml-index.xml
          - https://winx.fandom.com/fi/sitemap-newsitemapxml-index.xml
          - https://winx.fandom.com/fr/sitemap-newsitemapxml-index.xml
          - https://winx.fandom.com/gl/sitemap-newsitemapxml-index.xml
          - https://winx.fandom.com/hr/sitemap-newsitemapxml-index.xml
          - https://winx.fandom.com/hu/sitemap-newsitemapxml-index.xml
          - https://winx.fandom.com/it/sitemap-newsitemapxml-index.xml
          - https://winx.fandom.com/nl/sitemap-newsitemapxml-index.xml
          - https://winx.fandom.com/oc/sitemap-newsitemapxml-index.xml
          - https://winx.fandom.com/pl/sitemap-newsitemapxml-index.xml
          - https://winx.fandom.com/pt-br/sitemap-newsitemapxml-index.xml
          - https://winx.fandom.com/pt/sitemap-newsitemapxml-index.xml
          - https://winx.fandom.com/ro/sitemap-newsitemapxml-index.xml
          - https://winx.fandom.com/sl/sitemap-newsitemapxml-index.xml
          - https://winx.fandom.com/sr/sitemap-newsitemapxml-index.xml
          - https://winx.fandom.com/sv/sitemap-newsitemapxml-index.xml
          - https://winx.fandom.com/tr/sitemap-newsitemapxml-index.xml
          - https://winx.fandom.com/uk/sitemap-newsitemapxml-index.xml
    steps:
      - name: Cleanup pre-installed tools
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      
      - name: Install Wayback Machine Archiver
        run: |
          pip install wayback-machine-archiver

      - name: Archive the sitemap itself
        run: |
          archiver ${{ matrix.sitemaps }} --log INFO

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
        if: ${{ always() }}
      
      - name: Install Wayback Sitemap Archive
        run: npm install -g wayback-sitemap-archive
        if: ${{ success() }}

      - name: Archive wiki contents
        run: wayback-sitemap-archive ${{ matrix.sitemaps }}
        if: ${{ success() }}
        
  robots:
    name: Archive robots.txt
    runs-on: ubuntu-latest
    steps:
        - name: Setup Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.8'
            architecture: 'x64'
        
        - name: Install Wayback Machine Archiver
          run: |
            pip install wayback-machine-archiver
        
        - name: Archive robots.txt
          run: |
            archiver https://winx.fandom.com/robots.txt --log INFO
