name: Archive

on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  contents:
    name: Archive contents (${{ matrix.sitemaps }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sitemaps:
        #fandom automaticaly generates a sitemap of 3 sitemaps, but since a lot of them are big at the point that makes the workflow to timeout, the single ones are written separately to spin up different workflows
          # en
          - https://winx.fandom.com/sitemap-newsitemapxml-NS_0-id-1870-111148.xml
          - https://winx.fandom.com/sitemap-newsitemapxml-NS_14-id-1851-111149.xml
          - https://services.fandom.com/discussions-sitemap/sitemap/6708
          # bg
          - https://winx.fandom.com/bg/sitemap-newsitemapxml-index.xml
          # ca
          - https://winx.fandom.com/ca/sitemap-newsitemapxml-NS_0-id-4-2202.xml
          - https://winx.fandom.com/ca/sitemap-newsitemapxml-NS_14-id-68-1680.xml
          # cs
          - https://winx.fandom.com/cs/sitemap-newsitemapxml-NS_0-id-4-658.xml
          - https://winx.fandom.com/cs/sitemap-newsitemapxml-NS_14-id-95-103.xml
          - https://services.fandom.com/discussions-sitemap/sitemap/1154449
          # es
          - https://winx.fandom.com/es/sitemap-newsitemapxml-NS_0-id-2-22710.xml
          - https://winx.fandom.com/es/sitemap-newsitemapxml-NS_14-id-143-22613.xml
          - https://services.fandom.com/discussions-sitemap/sitemap/216303
          # fi
          - https://winx.fandom.com/fi/sitemap-newsitemapxml-index.xml
          # fr
          - https://winx.fandom.com/fr/sitemap-newsitemapxml-NS_0-id-7-4016.xml
          - https://winx.fandom.com/fr/sitemap-newsitemapxml-NS_14-id-45-3964.xml
          # gl
          - https://winx.fandom.com/gl/sitemap-newsitemapxml-NS_0-id-4-2174.xml
          - https://winx.fandom.com/gl/sitemap-newsitemapxml-NS_14-id-116-551.xml
          # hr
          - https://winx.fandom.com/hr/sitemap-newsitemapxml-NS_0-id-18-563.xml
          - https://winx.fandom.com/hr/sitemap-newsitemapxml-NS_14-id-315-553.xml
          - https://services.fandom.com/discussions-sitemap/sitemap/1803530
          # hu
          - https://winx.fandom.com/hu/sitemap-newsitemapxml-NS_0-id-4-512.xml
          - https://services.fandom.com/discussions-sitemap/sitemap/837615
          # it
          - https://winx.fandom.com/it/sitemap-newsitemapxml-NS_0-id-1461-17493.xml
          - https://winx.fandom.com/it/sitemap-newsitemapxml-NS_14-id-2018-15823.xml
          - https://services.fandom.com/discussions-sitemap/sitemap/1179215
          # nl
          - https://winx.fandom.com/nl/sitemap-newsitemapxml-NS_0-id-309-1801.xml
          - https://winx.fandom.com/nl/sitemap-newsitemapxml-NS_14-id-5-1400.xml
          # oc
          - https://winx.fandom.com/oc/sitemap-newsitemapxml-index.xml
          # pl
          - https://winx.fandom.com/pl/sitemap-newsitemapxml-NS_0-id-1546-6376.xml
          - https://winx.fandom.com/pl/sitemap-newsitemapxml-NS_14-id-1493-6032.xml
          - https://services.fandom.com/discussions-sitemap/sitemap/93104
          # pt-br
          - https://winx.fandom.com/sitemap-newsitemapxml-NS_0-id-1870-111168.xml
          - https://winx.fandom.com/sitemap-newsitemapxml-NS_14-id-1851-111149.xml
          - https://services.fandom.com/discussions-sitemap/sitemap/6708
          # pt
          - https://winx.fandom.com/pt/sitemap-newsitemapxml-NS_0-id-4-3059.xml
          - https://winx.fandom.com/pt/sitemap-newsitemapxml-NS_14-id-132-2714.xml
          # ro
          - https://winx.fandom.com/ro/sitemap-newsitemapxml-NS_0-id-4-5162.xml
          - https://winx.fandom.com/ro/sitemap-newsitemapxml-NS_14-id-68-5120.xml
          # sl
          - https://winx.fandom.com/sl/sitemap-newsitemapxml-NS_0-id-166-356.xml
          - https://winx.fandom.com/sl/sitemap-newsitemapxml-NS_14-id-81-217.xml
          - https://services.fandom.com/discussions-sitemap/sitemap/2353250
          # sr
          - https://winx.fandom.com/sr/sitemap-newsitemapxml-NS_0-id-4-694.xml
          - https://winx.fandom.com/sr/sitemap-newsitemapxml-NS_14-id-50-230.xml
          # sv
          - https://winx.fandom.com/sv/sitemap-newsitemapxml-index.xml
          # tr
          - https://winx.fandom.com/tr/sitemap-newsitemapxml-index.xml
          # uk
          - https://winx.fandom.com/uk/sitemap-newsitemapxml-NS_0-id-23-378.xml
          - https://services.fandom.com/discussions-sitemap/sitemap/1352009
    steps:
      - name: Cleanup pre-installed tools
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          
      - name: Cache
        id: cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: pre-archive-cache

      - name: Setup Node
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      
      - name: Install Wayback Sitemap Archive
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install -g wayback-sitemap-archive

      - name: Archive wiki contents
        run: wayback-sitemap-archive ${{ matrix.sitemaps }}
        
  robots:
    name: Archive robots.txt
    runs-on: ubuntu-latest
    steps:
        - name: Setup Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.8'
            architecture: 'x64'
        
        - name: Install Wayback Machine Archiver
          run: |
            pip install wayback-machine-archiver
        
        - name: Archive robots.txt
          run: |
            archiver https://winx.fandom.com/robots.txt --log INFO
